name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "keymap-drawer/**"
      - "keymap_drawer.config.yaml"
      - "README*"
      - ".gitignore"

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[no ci]')"
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
